### ISSUE TITLE
ruby/2.1.0/psych.rb:370:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 18 column 1 (Psych::SyntaxError)

### ISSUE THREAD

**Issue by cavangrl** [RailsApps/learn-rails#34]
Hi I checked the issues to see if anyone else is having this issue, seems not.

I'm working on a Rails application tutorial and have had the above error come up several times. When I was getting this error it seemed to only be a problem if I used one particular terminal window. I have since restarted the computer and now it is a problem regardless of what I do.

I went to the project on github and copied the information in 'secrets.yml' into my file in case that was the issue but doesn't help. In fact I'm not sure if that is even the file causing the problem because when I shift the code in that file and save it I still get the same error; at those times it points to a line that is now blank in the 'secrets.yml'

I  suspect it is to do with the 'secret' file or could it be changes the tutorial told me to make to my .bash_profile. Could that be causing the problems?  If so, how would I know? 
Is there a way to isolate and figure out what is causing the problem?

thank you

**Comment by Lobatomic** [comment]
You have to be really careful when writing the secrets.yml file, I had the same mistake and in my case the problem was an absent space in the line:
`domain_name:example.com`  
note the absent space between the colon and the word "example", when rewritten with the space (as the next line) the server runs successfully:
`domain_name: example.com`
I suggest you to just copy and paste the lines used in the training book, (as we are using environment variables with the same name, that shouldn't pose a problem) and use a good editor that shows the mistake, in my case, sublime editor shows the property and his value in different colors, then if you make a mistake, the two shows the same or wrong color.

**Comment by cdbBinary** [comment]
I had gone through all the suggestions and still nothing worked until I typed it in and it worked!

@DanielKehoe did I miss something along the way that should have flagged me of that?
I originally copied it in and formatted it using tabs until I read up on YAML specs. I then deleted the whole file, re-copied it in and formatted with spaces. I also made sure I had all my spacing between characters correct too. TIA!
