### ISSUE TITLE
 NameError at /  uninitialized constant Sprockets::SassCacheStore _app_views_layouts_application_html_erb___

### ISSUE THREAD

**Issue by berlingizmo** [RailsApps/learn-rails#75]
After initiating the command rails g layout:install --force command, I received the above mentioned error while trying to reload the page.

**Comment by active-developer** [comment]
I was following a tutorial from 2013

**Comment by DanielKehoe** [comment]
Which tutorial from 2013? I believe the command syntax has changed since then. Tell me the tutorial and I'll tell you if there is an updated version.

See the README page at
https://github.com/RailsApps/rails_layout
for the correct syntax.

And you can submit an issue if necessary at 
https://github.com/RailsApps/rails_layout/issues

If you've got an outdated version of the [Learn Ruby on Rails](http://learn-rails.com/learn-ruby-on-rails.html) book, you really should get the newest version of the book.
